### ISSUE TITLE
Remove your local deps

### ISSUE THREAD

**Issue by vicb** [blois/angular_transforms#14]
@blois do you think it could be possible to remove your local deps so that I can test this ?

The `pubspec.yaml` refers to local folders for both angular and di, you might be able to use [git refs](http://pub.dartlang.org/doc/dependencies.html#git-packages) ?

**Comment by vicb** [comment]
It seems to be related to the analyzer version...

**Comment by blois** [comment]
Yes, will work on this shortly.

**Comment by vicb** [comment]
Cool , thanks !

**Comment by blois** [comment]
Updated to work on latest published Angular (my earlier PRs were merged, using an override for the analyzer version).
